name: On Dispatch (Create & Deploy Release)

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
        description: The name of the branch to release.


jobs:
  validate:
    name: Validate Input
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Validate Branch
        run: |
          echo "Validating branch: ${{ inputs.branch }}"
          if [[ ! "${{ inputs.branch }}" =~ ^release/.* ]]; then
            echo "❌ Branch must start with 'release/'"
            exit 1
          fi
          echo "✅ Branch validation passed"

  release:
    name: Create Release
    uses: ./.github/workflows/callable-create-release.yml
    needs:
      - validate
    with:
      branch: ${{ inputs.branch }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-deploy:
    name: Build & Deploy Prod
    uses: ./.github/workflows/callable-deploy-prod.yml
    needs:
      - release
    with:
      version: ${{ needs.release.outputs.version }}
