name: On Dispatch (Create & Deploy Release)

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    uses: ./.github/workflows/callable-create-release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-deploy:
    name: Build & Deploy Prod
    uses: ./.github/workflows/callable-deploy-prod.yml
    needs:
      - release
    with:
      version: ${{ needs.release.outputs.version }}
