name: On Push (Release)

on:
  push:
    branches:
      - release/**

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/callable-test.yml

  notify:
    name: Send Notification About Testing Ready
    uses: ./.github/workflows/callable-notify.yml
    needs:
      - test
    with:
      message: Branch is ready for testing.
